# Generated by Django 3.2.6 on 2021-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ManyToManyField(to='CalorieCounter.Meal'),
        ),
    ]
