# Generated by Django 3.2.6 on 2021-08-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0002_day_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fats',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='proteins',
            new_name='protein',
        ),
    ]
