# Generated by Django 3.2.6 on 2021-08-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0004_meal_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
    ]
