# Generated by Django 3.2.6 on 2021-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0005_remove_meal_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
